### PR TITLE
Add Electron support to runtimes

### PR DESCRIPTION
**Pull request by Ivshti**

### CODE REVIEW

**Comment by unbornchikken** [comment]
It creates win-x64/electron.lib file with the following invalid content:

```xml
<?xml version="1.0" encoding="UTF-8"?>

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>AC7955586A298B1F</RequestId>
<HostId>2hSDFh6gI6rcjvea8vKG/vZsEANJnY18LGwLrtg7OqHjLkhMVzXUa3rfYN10n6gZ</HostId>
</Error>
```

And build failed.

In Dist.prototype._downloadLib there should be a special case for downloading lib file for electron runtime, and there should be a special winLibPAth value for this.

What's the path of the electron's windows library file in the distribution? I've tried node.lib but no luck.

**Comment by Ivshti** [comment]
It's node.lib but follows the same subdir logic as nw.js. Electron's dist urls are supposed to be compatible with node-gyp - that's why they use "node" for everything, but I can't explain why it follows NW.js subdir logic.

**Comment by unbornchikken** [comment]
ok, but Dist.winLibDir and Dist.winLibPath should be fixed too.

**Comment by unbornchikken** [comment]
```js
winLibDir: {
        get: function () {
            if (this.targetOptions.runtime === "nw" || this.targetOptions.runtime === "electron") {
                return path.join(this.internalPath, (this.targetOptions.isX64 ? "x64" : ""));
            }
            else {
                return path.join(this.internalPath, (this.targetOptions.isX64 ? "win-x64" : "win-x86"));
            }
        }
    },
    winLibPath: {
        get: function () {
            return path.join(this.winLibDir, (this.targetOptions.runtime === "electron" ? "node" : this.targetOptions.runtime) + ".lib");
        }
    }
```

**Comment by unbornchikken** [comment]
PR for a PR :)

**Comment by unbornchikken** [comment]
I think atom guys are drinking too mutch. By this way to build atom you should use nw-gyp with special dist-url option passed. Ain't nobody use this on windows?

**Comment by Ivshti** [comment]
Thanks. We should keep in mind that one of the NW.js guys is behind Electron, so my bet is they decided using node-gyp is better. And I agree in principle, seems easier. But they should probably fix the .lib paths to get it working for Windows or I'm missing something

**Comment by unbornchikken** [comment]
My explanation follows Occam's Razor principle, so we should accept that instead. :D Anyway, thanks for the PR! Merged. I can craft the next release later today (I hope), I have to go now.

**Comment by Ivshti** [comment]
Awesome, thanks!

**Pull request merged**
